### ISSUE TITLE
Error installing hook

### ISSUE THREAD

**Issue by Fogapod** [pre-commit/mirrors-isort#10]
pre-commit fails to install this hook on travis. This works on my machine with same python version, not sure what's causing this.

### .travis.yml
```yml
language: python
matrix:
  include:
    - name: "Python 3.7.1 on Xenial Linux"
      python: 3.7
      dist: xenial

env:
  - PIP_NO_CACHE_DIR=1 PIP_DISABLE_PIP_VERSION_CHECK=1

install:
  - pip3 install --upgrade pip
  - pip3 install -r requirements.txt
  - pip3 install pre-commit

script:
  - pre-commit run --all-files
```

### hook
```yml
repos:
  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v4.3.21
    hooks:
    - id: isort
```

### Result
```
$ pre-commit run --all-files
[INFO] Initializing environment for https://github.com/pre-commit/mirrors-isort.
[INFO] Initializing environment for https://github.com/ambv/black.
[INFO] Initializing environment for https://github.com/pre-commit/pre-commit-hooks.
[INFO] Initializing environment for https://github.com/pre-commit/mirrors-mypy.
[INFO] Installing environment for https://github.com/pre-commit/mirrors-isort.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
An unexpected error has occurred: CalledProcessError: Command: ('/home/travis/virtualenv/python3.7.1/bin/python', '-mvirtualenv', '/home/travis/.cache/pre-commit/repoj4s504mr/py_env-python3.7', '-p', '/home/travis/virtualenv/python3.7.1/bin/python')
Return code: 1
Expected return code: 0
Output: 
    Already using interpreter /home/travis/virtualenv/python3.7.1/bin/python
    Using real prefix '/opt/python/3.7.1'
    New python executable in /home/travis/.cache/pre-commit/repoj4s504mr/py_env-python3.7/bin/python
    Overwriting /home/travis/.cache/pre-commit/repoj4s504mr/py_env-python3.7/lib/python3.7/distutils/__init__.py with new content
    Installing setuptools, pip, wheel...
    
      Complete output from command /home/travis/.cache/...python3.7/bin/python - setuptools pip wheel:
      Exception:
    Traceback (most recent call last):
      File "/home/travis/virtualenv/python3.7.1/lib/python3.7/site-packages/virtualenv_support/pip-18.1-py2.py3-none-any.whl/pip/_internal/cli/base_command.py", line 143, in main
        status = self.run(options, args)
      File "/home/travis/virtualenv/python3.7.1/lib/python3.7/site-packages/virtualenv_support/pip-18.1-py2.py3-none-any.whl/pip/_internal/commands/install.py", line 259, in run
        with self._build_session(options) as session:
      File "/home/travis/virtualenv/python3.7.1/lib/python3.7/site-packages/virtualenv_support/pip-18.1-py2.py3-none-any.whl/pip/_internal/cli/base_command.py", line 76, in _build_session
        if options.cache_dir else None
      File "/home/travis/.cache/pre-commit/repoj4s504mr/py_env-python3.7/lib/python3.7/posixpath.py", line 80, in join
        a = os.fspath(a)
    TypeError: expected str, bytes or os.PathLike object, not int
    ----------------------------------------
    ...Installing setuptools, pip, wheel...done.
    
Errors: 
    Traceback (most recent call last):
      File "/opt/python/3.7.1/lib/python3.7/runpy.py", line 193, in _run_module_as_main
        "__main__", mod_spec)
      File "/opt/python/3.7.1/lib/python3.7/runpy.py", line 85, in _run_code
        exec(code, run_globals)
      File "/home/travis/virtualenv/python3.7.1/lib/python3.7/site-packages/virtualenv.py", line 2462, in <module>
        main()
      File "/home/travis/virtualenv/python3.7.1/lib/python3.7/site-packages/virtualenv.py", line 762, in main
        symlink=options.symlink,
      File "/home/travis/virtualenv/python3.7.1/lib/python3.7/site-packages/virtualenv.py", line 1015, in create_environment
        install_wheel(to_install, py_executable, search_dirs, download=download)
      File "/home/travis/virtualenv/python3.7.1/lib/python3.7/site-packages/virtualenv.py", line 968, in install_wheel
        call_subprocess(cmd, show_stdout=False, extra_env=env, stdin=SCRIPT)
      File "/home/travis/virtualenv/python3.7.1/lib/python3.7/site-packages/virtualenv.py", line 854, in call_subprocess
        raise OSError("Command {} failed with error code {}".format(cmd_desc, proc.returncode))
    OSError: Command /home/travis/.cache/...python3.7/bin/python - setuptools pip wheel failed with error code 2
    
Check the log at /home/travis/.cache/pre-commit/pre-commit.log
The command "pre-commit run --all-files" exited with 1.
```

**Comment by Fogapod** [comment]
Just realized this is not an isort hook issue, it's just first hook to be installed

**Comment by Fogapod** [comment]
It looks like env variables `PIP_NO_CACHE_DIR=1 PIP_DISABLE_PIP_VERSION_CHECK=1` broke pre-commit. Removing them resolved issue. Is this a bug?

**Comment by asottile** [comment]
those will break _pip_ in general:

```console
$ PIP_NO_CACHE_DIR=1 pip install astpretty
Exception:
Traceback (most recent call last):
  File "/home/asottile/workspace/babi/x/venv/lib/python3.6/site-packages/pip/_internal/cli/base_command.py", line 143, in main
    status = self.run(options, args)
  File "/home/asottile/workspace/babi/x/venv/lib/python3.6/site-packages/pip/_internal/commands/install.py", line 259, in run
    with self._build_session(options) as session:
  File "/home/asottile/workspace/babi/x/venv/lib/python3.6/site-packages/pip/_internal/cli/base_command.py", line 76, in _build_session
    if options.cache_dir else None
  File "/home/asottile/workspace/babi/x/venv/lib/python3.6/posixpath.py", line 80, in join
    a = os.fspath(a)
TypeError: expected str, bytes or os.PathLike object, not int
Traceback (most recent call last):
  File "/home/asottile/workspace/babi/x/venv/bin/pip", line 10, in <module>
    sys.exit(main())
  File "/home/asottile/workspace/babi/x/venv/lib/python3.6/site-packages/pip/_internal/__init__.py", line 78, in main
    return command.main(cmd_args)
  File "/home/asottile/workspace/babi/x/venv/lib/python3.6/site-packages/pip/_internal/cli/base_command.py", line 184, in main
    timeout=min(5, options.timeout)
  File "/home/asottile/workspace/babi/x/venv/lib/python3.6/site-packages/pip/_internal/cli/base_command.py", line 76, in _build_session
    if options.cache_dir else None
  File "/home/asottile/workspace/babi/x/venv/lib/python3.6/posixpath.py", line 80, in join
    a = os.fspath(a)
TypeError: expected str, bytes or os.PathLike object, not int
```

The "correct" format is `PIP_NO_CACHE_DIR=off`

It appears newer pip also fixes this, the allow the format you're using in pip 19+ -- to use a newer pip, upgrade the version of `virtualenv` installed alongside pre-commit
